name: flutter_helper
description: A new Flutter package project.
version: 0.0.13
homepage: "https://flutter.dev/"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  quiver: ^3.0.1
  image_picker: ^0.8.0+1
  firebase_storage: ^8.1.1
  firebase_auth: ^1.3.0
  cloud_functions: ^1.1.1
  rxdart: ^0.27.1
  cloud_firestore: ^2.2.1
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter